export const property = {
  name: 'property',
  title: 'Property',
  type: 'document',
  fields: [
    {
      name: 'title',
      title: 'Property Title',
      type: 'string',
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: { source: 'title' },
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'description',
      title: 'Property Description',
      type: 'text',
      rows: 4,
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'price',
      title: 'Price (₦)',
      type: 'number',
      validation: (rule: any) => rule.required().positive(),
    },
    {
      name: 'currency',
      title: 'Currency',
      type: 'string',
      initialValue: 'NGN',
      options: {
        list: [
          { title: 'Nigerian Naira (₦)', value: 'NGN' },
          { title: 'US Dollar ($)', value: 'USD' },
          { title: 'British Pound (£)', value: 'GBP' },
        ],
      },
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'location',
      title: 'Location/City',
      type: 'string',
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'state',
      title: 'State',
      type: 'string',
      options: {
        list: [
          'Abia',
          'Adamawa',
          'Akwa Ibom',
          'Anambra',
          'Bauchi',
          'Bayelsa',
          'Benue',
          'Borno',
          'Cross River',
          'Delta',
          'Ebonyi',
          'Edo',
          'Ekiti',
          'Enugu',
          'FCT',
          'Gombe',
          'Imo',
          'Jigawa',
          'Kaduna',
          'Kano',
          'Katsina',
          'Kebbi',
          'Kogi',
          'Kwara',
          'Lagos',
          'Nasarawa',
          'Niger',
          'Ogun',
          'Ondo',
          'Osun',
          'Oyo',
          'Plateau',
          'Rivers',
          'Sokoto',
          'Taraba',
          'Yobe',
          'Zamfara',
        ],
      },
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'bedrooms',
      title: 'Bedrooms',
      type: 'number',
      validation: (rule: any) => rule.required().min(0),
    },
    {
      name: 'bathrooms',
      title: 'Bathrooms',
      type: 'number',
      validation: (rule: any) => rule.required().min(0),
    },
    {
      name: 'area',
      title: 'Area (sqm)',
      type: 'number',
      validation: (rule: any) => rule.required().positive(),
    },
    {
      name: 'propertyType',
      title: 'Property Type',
      type: 'string',
      options: {
        list: [
          { title: 'For Sale', value: 'sale' },
          { title: 'For Rent', value: 'rent' },
        ],
      },
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'category',
      title: 'Category',
      type: 'string',
      options: {
        list: [
          { title: 'House', value: 'house' },
          { title: 'Apartment', value: 'apartment' },
          { title: 'Land', value: 'land' },
          { title: 'Commercial', value: 'commercial' },
        ],
      },
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'images',
      title: 'Property Images',
      type: 'array',
      of: [
        {
          type: 'url',
          validation: (rule: any) => rule.required(),
        },
      ],
      validation: (rule: any) => rule.required().min(1),
    },
    {
      name: 'features',
      title: 'Property Features',
      type: 'array',
      of: [
        {
          type: 'string',
        },
      ],
      options: {
        layout: 'tags',
      },
    },
    {
      name: 'agent',
      title: 'Agent Information',
      type: 'object',
      fields: [
        {
          name: 'name',
          title: 'Agent Name',
          type: 'string',
          validation: (rule: any) => rule.required(),
        },
        {
          name: 'email',
          title: 'Agent Email',
          type: 'string',
          validation: (rule: any) => rule.required().email(),
        },
        {
          name: 'phone',
          title: 'Agent Phone',
          type: 'string',
          validation: (rule: any) => rule.required(),
        },
        {
          name: 'image',
          title: 'Agent Image',
          type: 'url',
        },
      ],
      validation: (rule: any) => rule.required(),
    },
    {
      name: 'createdAt',
      title: 'Created At',
      type: 'datetime',
      initialValue: () => new Date().toISOString(),
      validation: (rule: any) => rule.required(),
    },
  ],
};
